apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: example-runnerdeploy
  namespace: actions-runner-system
spec:
  replicas: 1
  template:
    spec:
      repository: juang903/github-runner-on-aks
      #organization: <YOUR ORG NAME IF WANT TO WORK AT ORG LEVEL>  
      image: ghcr.io/juang903/github-runner-on-aks:main
      imagePullSecrets:
      - name: ghcrsecret